In [1]:
import tensorflow as tf


In [2]:
tenser_0d=tf.constant(1)

In [4]:
tenser_0d

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
print(tenser_0d)

tf.Tensor(1, shape=(), dtype=int32)


In [7]:
tenser_0d.ndim

0

In [16]:
tenser1d=tf.constant([1,2,3,4,5,6,7])
print(tenser1d.shape)

(7,)


In [22]:
tenser2d=tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9]], dtype=tf.int64)
print(tenser2d)
print(tenser2d.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)
(3, 3)


In [15]:
tenser3d=tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]]
                      ], dtype=tf.int64)
print(tenser3d)
print(tenser3d.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int64)
3


In [20]:
print(tenser1d[1:4:2])

tf.Tensor([2 4], shape=(2,), dtype=int32)


In [23]:
print(tenser2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)


In [28]:
print(tenser2d[0:3:2,0:3:2])

tf.Tensor(
[[1 3]
 [7 9]], shape=(2, 2), dtype=int64)
